version: "3"
services:

  web:
    image: golosblockchain/web-ui:latest
    build: .
    restart: always
    command: bash -c "cd db && ../node_modules/.bin/sequelize db:migrate && cd .. && yarn run production"
    volumes:
      - ./default.json:/var/app/config/default.json
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SDC_TARANTOOL_HOSTNAME: datastore
      SDC_DATABASE_URL: mysql://golosdev:golosdev@db:3306/golosdev
      SDC_CLIENT_WEBSOCKET_URL: https://api.golos.id
      SDC_SERVER_WEBSOCKET_URL: https://api.golos.id
      SDC_REGISTRAR_ACCOUNT: your-account
      SDC_REGISTRAR_SIGNINGKEY: active-key
      SDC_GMAIL_SEND_USER: your-mail@gmail.com
      SDC_GMAIL_SEND_PASS: your-password

  db:
    image: mysql:5.7.22
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: golosdev
      MYSQL_USER: golosdev
      MYSQL_PASSWORD: golosdev
      MYSQL_ROOT_PASSWORD: golosdev

  datastore:
    image: golosblockchain/web-ui:datastore
    build:
      context: https://github.com/golos-blockchain/golosnotify.git
      dockerfile: Dockerfile-datastore
    volumes:
      - ./data/tarantool:/var/lib/tarantool
    ports:
      - "3301:3301"

  datafeed:
    image: golosblockchain/web-ui:datafeed
    build:
      context: https://github.com/golos-blockchain/golosnotify.git
      dockerfile: Dockerfile-datafeed
    restart: unless-stopped
    depends_on:
      - datastore
    environment:
      NODE_URL: https://api.golos.id
      TARANTOOL_HOST: datastore