version: "3"
services:

  web:
    image: golosblockchain/web-ui:latest
    restart: always
    build: .
    volumes:
      - ./config/default.json:/var/app/config/default.json
    ports:
      - "8080:8080"
    environment:
      SDC_CLIENT_WEBSOCKET_URL: https://api-full.golos.id
      SDC_SERVER_WEBSOCKET_URL: https://api-full.golos.id
      SDC_MSGS_WEBSOCKET_URL: wss://api-full.golos.id/ws
      
  # other parameters in config/custom-environment-variables.json
